spring.application.name=nutritionist-service
spring.config.import=optional:configserver:http://config-service:8888
management.endpoints.web.exposure.include="health,info"
management.endpoint.health.probes.enabled=true